# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: task_manager_postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: task_user
      POSTGRES_DB: task_db
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
  web:
    # Берем Dockerfile из каталога app
    build: ./task_project
    # Запускаем тестовый сервер
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # куда будут помещены данные из каталога app
    volumes:
      - ./task_project/:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    depends_on:
      - db
