# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: task_manager_postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: task_user
      POSTGRES_DB: task_db
      # PGDATA: /home/eh97979/task_manager_app/docker/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"
